// AutoValor - Complete Mexican Automotive Market Catalog
// Generated from Guía Autoprecios Lobato - Feb 2026

const MAKES_DATA = {
  "Acura": ["ADX","ILX","Integra","MDX","NSX","RDX","RLX","TLX"],
  "Alfa Romeo": ["4C","Giulia","Giulietta","MiTo","Stelvio","Tonale"],
  "Audi": ["A1","A1 Sportback","A3","A3 Cabrio","A4","A5","A6","A7","A8","e-tron","Q2","Q3","Q5","Q6 e-tron","Q7","Q8","R8","TT"],
  "BAIC": ["BJ20","BJ40","D20","EU5","X25","X30","X35","X55","X65"],
  "Bestune": ["B70","B70S","NAT","T77","T99"],
  "BMW": ["i3","i4","i5","i7","i8","iX","iX1","iX2","iX3","Serie 1","Serie 2","Serie 3","Serie 4","Serie 5","Serie 7","Serie 8","X1","X2","X3","X4","X5","X6","X7"],
  "Buick": ["Enclave","Encore","Envision","Envista","LaCrosse","Regal","Verano"],
  "BYD": ["Atto 8","Dolphin","Dolphin Mini","Han","King DM-i","M9 Minivan","Seal","Sealion 7","Song Plus DM-i","Song Pro DM-i","Tang","Yuan Plus","Yuan Pro"],
  "Cadillac": ["ATS","CTS","Escalade","Escalade IQ","Lyriq","Optiq","SRX","XT4","XT5"],
  "Changan": ["Alsvin","CS35 Plus","CS55 Plus","CS75 Pro","CS95 Plus","Deepal S05","Deepal S07","UNI-K"],
  "Chevrolet": ["Aveo","Beat","Blazer","Blazer EV","Bolt EUV","Bolt EV","Camaro","Captiva","Cavalier","Corvette","Cruze","Equinox","Equinox EV","Groove","Malibu","Onix","Sonic","Spark","Suburban","Tahoe","Tracker","Traverse","Trax","Volt"],
  "Chirey": ["Arrizo 8","Omoda C5","Tiggo 2 Pro","Tiggo 4 Pro","Tiggo 7 Pro","Tiggo 8 Pro"],
  "Chrysler": ["Pacifica","Town and Country"],
  "Cupra": ["Ateca","Formentor","León","Terramar"],
  "Dodge": ["Attitude","Challenger","Charger","Dart","Durango","Grand Caravan","Journey","Neón","Vision"],
  "Ferrari": ["Ferrari"],
  "Fiat": ["500","500L","500X","Mobi","Palio","Pulse","Uno"],
  "Ford": ["Bronco","Bronco Sport","EcoSport","Edge","Escape","Expedition","Explorer","Fiesta","Figo","Focus","Fusion","Mustang","Mustang Mach-E","Taurus","Territory","Transit"],
  "GAC": ["Aion Y","Emkoo","Emzoom","GN8","GS8"],
  "Geely": ["Cityray","Coolray","Emgrand","Monjaro","Okavango"],
  "GMC": ["Acadia","Hummer EV","Sierra","Terrain","Yukon"],
  "GWM": ["Haval H6","Haval Jolion","Tank 300","Tank 500"],
  "Honda": ["Accord","BR-V","City","Civic","Civic Type R","CR-V","CR-Z","Fit","Insight","Odyssey","Pilot"],
  "Hyundai": ["Accent","Creta","Creta Grand","Elantra","Grand i10","Ioniq","Ioniq 5","Palisade","Santa Fe","Sonata","Starex","Tucson"],
  "INEOS": ["Grenadier"],
  "Infiniti": ["Q50","Q60","QX30","QX50","QX55","QX60","QX80"],
  "JAC": ["EJ7","J7","Jac 4","Jac 6","Jac 8","Sei4","Sei7"],
  "JAECOO": ["Jaecoo 5","Jaecoo 7"],
  "Jaguar": ["E-Pace","F-Pace","F-Type","XE","XF","XJ"],
  "Jeep": ["Cherokee","Commander","Compass","Grand Cherokee","Patriot","Renegade","Wrangler"],
  "Jetour": ["Dashing","X70","X90 Plus"],
  "Kia": ["Forte","K4","Niro","Optima","Seltos","Sorento","Soul","Sportage","Stinger","Telluride"],
  "Land Rover": ["Defender","Discovery","Range Rover","Range Rover Evoque","Range Rover Sport","Range Rover Velar"],
  "Lexus": ["ES","GX","IS","LC","LS","LX","NX","RC","RX","UX"],
  "Lincoln": ["Aviator","Continental","Corsair","Nautilus","Navigator"],
  "Maserati": ["Ghibli","Grecale","GranTurismo","Levante","Quattroporte"],
  "Mazda": ["CX-3","CX-30","CX-5","CX-50","CX-9","CX-90","Mazda2","Mazda3","Mazda5","Mazda6","MX-5"],
  "Mercedes-Benz": ["Clase A","Clase B","Clase C","Clase CLA","Clase CLS","Clase E","Clase G","Clase GLA","Clase GLB","Clase GLC","Clase GLE","Clase GLS","Clase S","Clase SL","Clase SLC","Clase V","EQB","EQC","EQE","Sprinter"],
  "MG": ["Cyberster","MG4","MG7","MG GT","MG ONE","RX5"],
  "Mini": ["Clubman","Convertible","Cooper","Countryman","Paceman"],
  "Mitsubishi": ["ASX","Eclipse Cross","Lancer","Mirage","Montero","Outlander","Outlander Sport","Xpander"],
  "Nissan": ["370Z","Altima","Armada","GT-R","Juke","Kicks","Leaf","Magnite","March","NV350 Urvan","Pathfinder","Tiida","Tsuru GS","Versa","X-Trail"],
  "Omoda": ["C5","C9"],
  "Peugeot": ["208","301","308","508","2008","3008","5008","Partner","RCZ","Rifter"],
  "Porsche": ["718 Boxster","718 Cayman","911","Cayenne","Macan","Panamera","Taycan"],
  "Renault": ["Arkana","Captur","Clio","Duster","Kardian","Koleos","Kwid","Logan","Sandero","Stepway"],
  "Seat": ["Arona","Ateca","Ibiza","León","Tarraco","Toledo"],
  "SERES": ["3","5","7"],
  "Smart": ["Smart EQ"],
  "Subaru": ["BRZ","Crosstrek","Forester","Impreza","Legacy","Outback","WRX"],
  "Suzuki": ["Baleno","Ciaz","Ertiga","Fronx","Grand Vitara","Ignis","Jimny","Swift","Vitara"],
  "Tesla": ["Cybertruck","Model 3","Model S","Model X","Model Y"],
  "Toyota": ["4Runner","Avanza","C-HR","Camry","Corolla","Corolla GR","Hiace","Land Cruiser","Prius","RAV4","Raize","Sequoia","Sienna","Tacoma","Yaris"],
  "Volkswagen": ["Amarok","Beetle","Golf A6","Golf A7","GTI A7","GTI A8","ID.4","Jetta A4","Jetta A6","Jetta A7","Nivus","Passat","Polo","T-Cross","Taigun","Tera","Teramont","Tiguan","Touareg","Transporter","Vento","Virtus"],
  "Volvo": ["C40","EX30","EX40","V40","V60","XC40","XC60","XC90"],
  "Zeekr": ["001","7X","X"]
};

const TRIMS_DATA = {
  "Jetta A7": ["Trendline L4 1.4T TA8","Comfortline L4 1.4T TA8","Sportline L4 1.4T TA8 piel","R-Line L4 1.4T TM6","Highline L4 1.4T TA6 piel","GLI L4 2.0T DSG7 piel"],
  "Jetta A6": ["Base L4 2.0 TM5","Live L4 2.0 TM5","Style L4 2.0 TM5","Trendline L5 2.5 TM5","Comfortline L5 2.5 TM5","Sportline L5 2.5 TM5 piel","GLI L4 2.0T TM6 piel"],
  "Jetta A4": ["2.0 Base TM5","2.0 GL TM5","2.5 Trendline TM5","2.5 Comfortline TM5","2.5 Sportline TM5 piel"],
  "Versa": ["Sense MT","Sense CVT","Advance CVT","Exclusive CVT"],
  "Kicks": ["Sense CVT","Advance CVT","Exclusive CVT"],
  "March": ["Sense MT","Advance MT","Advance CVT","Exclusive CVT"],
  "X-Trail": ["Sense CVT","Advance CVT","Exclusive CVT","Exclusive 4x4 CVT"],
  "Altima": ["Sense CVT","Advance CVT","Exclusive CVT"],
  "Civic": ["Uniq CVT","Sport CVT","Turbo CVT","Si TM","Type R TM"],
  "City": ["Uniq CVT","Sport CVT","Prime CVT"],
  "Accord": ["Sport CVT","Touring CVT","Hybrid CVT"],
  "CR-V": ["i-Style CVT","Sport CVT","Turbo Plus CVT","Hybrid CVT"],
  "Corolla": ["Base CVT","LE CVT","SE CVT","XSE CVT","XLE CVT"],
  "Camry": ["LE CVT","SE CVT","XSE CVT","XLE CVT","TRD CVT"],
  "RAV4": ["XLE CVT","XLE Premium CVT","Limited CVT","TRD Off-Road","Adventure 4x4"],
  "Yaris": ["Core MT","S MT","S CVT","R CVT"],
  "C-HR": ["Base CVT","Limited CVT"],
  "4Runner": ["SR5 TA5","TRD Off-Road TA5","Limited TA5","TRD Pro TA5"],
  "Avanza": ["S TM","S TA","Premium TM","Premium TA"],
  "Aveo": ["LS TM","LS TA","LT TM","LT TA","LTZ TA"],
  "Tracker": ["LS CVT","LT CVT","RS CVT","Premier CVT"],
  "Spark": ["LT TM","LT TA","Active TM","Active TA"],
  "Cavalier": ["LS TM","LS TA","LT TA","RS TA","Premier TA"],
  "Onix": ["LS TM","LS TA","LT TA","LTZ TA","RS TA"],
  "Equinox": ["LS FWD TA","LT FWD TA","LT AWD TA","Premier FWD TA","Premier AWD TA"],
  "Mazda3": ["i Touring TA6","i Grand Touring TA6","s Sport TM6","s Grand Touring TA6"],
  "CX-5": ["i Sport TM","i Grand Touring TA","s Grand Touring TA","s Signature TA"],
  "CX-30": ["i Sport TA","i Grand Touring TA","s Grand Touring TA"],
  "Mazda2": ["i Sport TM","i Grand Touring TA"],
  "Tucson": ["GLS TM","GLS TA","Limited TA","Premium TA"],
  "Creta": ["GLS MT","GLS TA","Limited TA","Premium TA"],
  "Elantra": ["GLS TM","GLS TA","Limited TA","N Line TA"],
  "Accent": ["GL MT","GL TA","GLS MT","GLS TA"],
  "Sportage": ["LX TM","EX TA","EX Plus TA","SX TA"],
  "Seltos": ["LX TM","EX TA","EX Plus TA","SX TA"],
  "Forte": ["LX TM","EX TA","GT Line TA","EX Plus TA"],
  "Explorer": ["Base TA","XLT TA","Limited TA","Platinum TA","ST TA"],
  "Escape": ["S FWD TA","SE FWD TA","SEL FWD TA","Titanium FWD TA"],
  "Bronco": ["Base TM","Big Bend TA","Black Diamond TA","Badlands TA","Wildtrak TA"],
  "Mustang": ["EcoBoost TM","EcoBoost Premium TA","GT TM","GT Premium TA","Mach 1 TM"],
  "Serie 3": ["320i Sport Line TA8","320i M Sport TA8","330i M Sport TA8","M340i TA8"],
  "Serie 5": ["520i TA8","530i M Sport TA8","540i M Sport TA8","M550i TA8"],
  "X3": ["xDrive20i TA8","xDrive30i M Sport TA8","M40i TA8"],
  "X5": ["xDrive40i TA8","xDrive40e TA8","M50i TA8"],
  "Clase C": ["C180 Avantgarde TA7","C200 Avantgarde TA9","C300 AMG Line TA9"],
  "Clase E": ["E200 Avantgarde TA9","E300 Avantgarde TA9","E450 AMG Line TA9"],
  "Clase GLC": ["GLC200 TA9","GLC300 4Matic TA9","GLC43 AMG TA9"],
  "Clase A": ["A200 Progressive TA7","A250 AMG Line TA7"],
  "A4": ["Dynamic L4 2.0T TA7","Select L4 2.0T TA7","S line L4 2.0T TA7"],
  "A3": ["Select L4 1.4T TA7","S line L4 2.0T TA7"],
  "Q5": ["Dynamic L4 2.0T TA7","Select L4 2.0T TA7","S line L4 2.0T TA7","SQ5 V6 3.0T TA8"],
  "Q3": ["Dynamic L4 1.4T TA6","Select L4 1.4T TA6","S line L4 2.0T TA7"],
  "Tiguan": ["Trendline L4 1.4T TA6","Comfortline L4 1.4T TA6","Highline L4 2.0T TA7","R-Line L4 2.0T TA7"],
  "T-Cross": ["Trendline L4 1.0T TA6","Comfortline L4 1.0T TA6","Highline L4 1.0T TA7"],
  "Polo": ["Trendline L4 1.6 TM5","Comfortline L4 1.6 TA6","Highline L4 1.6 TA6"],
  "Vento": ["Comfortline L4 1.6 TA6","Highline L4 1.6 TA6","GLI L4 1.4T TA7"],
  "Wrangler": ["Sport TM","Sahara TA","Rubicon TM","Willys TA"],
  "Grand Cherokee": ["Laredo TA","Limited TA","Overland TA","Summit TA","Trailhawk TA"],
  "Compass": ["Sport TM","Latitude TA","Limited 4x4 TA","Trailhawk 4x4 TA"],
  "Santa Fe": ["GLS TM","GLS TA","Limited TA","Premium TA"],
  "Cayenne": ["Cayenne TA8","Cayenne S TA8","Cayenne GTS TA8","Cayenne Turbo TA8"],
  "Macan": ["Macan TA7","Macan S TA7","Macan GTS TA7","Macan Turbo TA7"],
  "911": ["Carrera TA8","Carrera S TA8","Carrera 4S TA8","Turbo TA8","Turbo S TA8"],
  "XC40": ["Momentum TA8","R-Design TA8","Inscription TA8","Recharge EV"],
  "XC60": ["Momentum TA8","R-Design TA8","Inscription TA8","Polestar TA8"],
  "Model 3": ["Standard Range","Long Range AWD","Performance AWD"],
  "Model Y": ["Long Range AWD","Performance AWD"],
  "Duster": ["Expression MT","Zen MT","Journey MT","Journey CVT"],
  "Kwid": ["Life MT","Zen MT","Outsider MT"],
  "Sandero": ["Life MT","Zen MT","Stepway CVT"],
  "Clio": ["Zen MT","Intens MT","R.S. Line MT"],
  "Captur": ["Zen MT","Intens CVT","R.S. Line CVT"],
  "Koleos": ["Zen CVT","Intens CVT"],
  "Arkana": ["Zen CVT","Intens CVT","R.S. Line CVT"],
  "Kardian": ["Evolution CVT","Techno CVT"],
  "Ibiza": ["Reference TM","Style TM","FR TM"],
  "León": ["Style TM","FR TM","Cupra TM"],
  "Ateca": ["Style TM","FR TM","Cupra TA"],
  "Forester": ["Base CVT","Limited CVT","Sport CVT","Touring CVT"],
  "Outback": ["Base CVT","Limited CVT","Touring CVT","Wilderness CVT"],
  "WRX": ["Base TM6","Limited TM6","STI TM6"],
  "Vitara": ["GL+ TM","GLX+ TA"],
  "Grand Vitara": ["GL TM","GLX TM","GLX+ TA"],
  "Swift": ["GL TM","GLX TM","Sport TM"],
  "Jimny": ["GL TM","JLX TM"],
  "Escalade": ["Luxury TA10","Premium Luxury TA10","Sport Platinum TA10"],
  "XT5": ["Premium Luxury FWD TA9","Premium Luxury AWD TA9","Sport AWD TA9"],
  "Navigator": ["Standard TA10","Reserve TA10","Black Label TA10"],
  "Defender": ["90 S TA8","110 S TA8","110 X TA8","130 X TA8"],
  "Range Rover": ["SE TA8","HSE TA8","Autobiography TA8","SV TA8"],
  "Range Rover Sport": ["S TA8","SE TA8","HSE TA8","Autobiography TA8"],
  "Range Rover Evoque": ["S TA9","SE TA9","HSE TA9"],
  "F-Pace": ["S TA8","SE TA8","HSE TA8","SVR TA8"],
  "Q50": ["Sensación TA7","Perfección TA7","Red Sport TA7"],
  "QX50": ["Sensación CVT","Perfección CVT","Autograph CVT"],
  "QX60": ["Sensación CVT","Perfección CVT","Autograph CVT"],
  "Haval H6": ["HEV TA7","PHEV TA7"],
  "Haval Jolion": ["HEV TA7","PHEV TA7"],
  "Tank 300": ["Luxury TA8","Ultra TA8"],
  "Sportage": ["LX TM","EX TA","EX Plus TA","SX TA"],
  "Telluride": ["LX TA8","S TA8","EX TA8","SX TA8"],
  "Sorento": ["LX TA6","EX TA6","SX TA6","X-Line TA6"],
  "Eclipse Cross": ["ES CVT","SE CVT","SEL CVT"],
  "Outlander": ["ES CVT","SE CVT","SEL CVT","PHEV CVT"],
  "Xpander": ["GLX MT","GLS MT","GLS TA"],
  "208": ["Like MT5","Allure MT5","GT MT8"],
  "2008": ["Like MT5","Allure MT5","GT TA8"],
  "3008": ["Active TA8","Allure TA8","GT TA8"],
  "5008": ["Allure TA8","GT TA8"]
};

module.exports = { MAKES_DATA, TRIMS_DATA };
